Repository junhyeon0218/calog-ui, pull requests merged in 2024-03, with the labels that each got.

#1 🎨 Design: Input 컴포넌트 분리 및 email, password input ui 구현
  public/images/.gitkeep
  public/images/eye-off.png
  public/images/eye-on.png
  src/components/.gitkeep
  src/components/Common/Input/index.tsx
Labels: 디자인, 공통디자인

#2 ✨ Feat: 메인페이지 컨텐츠
  public/images/landing/testImage1.avif
  src/components/landing/content/index.tsx
Labels: 디자인

#3 ♻️ Refactor: input 컴포넌트 로직 수정
  public/images/input/eye-off.png
  public/images/input/eye-on.png
  src/components/common/header/index.tsx
  src/components/common/input/index.tsx
Labels: 리팩토링

#5 🎨 Design: footer ui 구현
  public/images/landing/Instagram-icon.svg
  public/images/landing/facebook-icon.svg
  src/components/landing/footer/index.tsx
  src/pages/index.tsx
Labels: 디자인

#6 🎨 Design: 메인페이지 반응형 ui 구현
  src/components/landing/content/index.tsx
  src/pages/index.tsx
Labels: 디자인
